# Generated by Django 5.2.7 on 2025-10-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('requests', '0001_initial'),
        ('users', '0002_alter_user_priority_id_alter_user_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method_id',
            field=models.ForeignKey(db_column='method_id', on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.PROTECT, to='requests.request'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
