# Generated by Django 5.2.7 on 2025-10-16 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doccatalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPurpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'request_purposes',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'request_statuses',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
                ('purpose_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='requests.requestpurpose')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='requests.requeststatus')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='RequestedDocuments',
            fields=[
                ('reqdoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('doctype_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='doccatalog.documenttype')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
            options={
                'db_table': 'requested_documents',
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requests.requeststatus')),
            ],
            options={
                'db_table': 'request_history',
            },
        ),
    ]
