# Generated by Django 5.2.7 on 2025-10-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccatalog', '0001_initial'),
        ('requests', '0001_initial'),
        ('users', '0002_alter_user_priority_id_alter_user_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purpose_id',
            field=models.ForeignKey(db_column='purpose_id', on_delete=django.db.models.deletion.RESTRICT, to='requests.requestpurpose'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, to='requests.requeststatus'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='users.user'),
        ),
        migrations.AlterField(
            model_name='requesteddocuments',
            name='doctype_id',
            field=models.ForeignKey(db_column='doctype_id', on_delete=django.db.models.deletion.RESTRICT, to='doccatalog.documenttype'),
        ),
        migrations.AlterField(
            model_name='requesteddocuments',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='request_id',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='requests.request'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='requests.requeststatus'),
        ),
    ]
