# Generated by Django 5.2.7 on 2025-11-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='purpose_id',
        ),
        migrations.AddField(
            model_name='requesteddocuments',
            name='purpose_id',
            field=models.ForeignKey(db_column='purpose_id', default=1, on_delete=django.db.models.deletion.RESTRICT, to='requests.requestpurpose'),
        ),
    ]
