# Generated by Django 5.2.7 on 2025-11-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=15)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('template_msg', models.TextField()),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=15)),
                ('reference_table', models.CharField(max_length=50)),
                ('reference_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
