# Generated by Django 5.2.7 on 2025-10-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('users', '0002_alter_user_priority_id_alter_user_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
