# Generated by Django 5.2.7 on 2025-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=15)),
                ('template_msg', models.TextField()),
            ],
            options={
                'db_table': 'templates',
            },
        ),
    ]
