# Generated by Django 5.2.7 on 2025-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
