# Generated by Django 5.2.7 on 2025-10-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCategory',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('pregnant', 'Pregnant'), ('pwd', 'Person with Disability'), ('senior', 'Senior Citizen')], max_length=30)),
                ('priority_level', models.IntegerField()),
            ],
            options={
                'db_table': 'priority_categories',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RoleStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'role_statuses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('middle_name', models.CharField(blank=True, max_length=35, null=True)),
                ('last_name', models.CharField(blank=True, max_length=35, null=True)),
                ('student_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.prioritycategory')),
                ('role_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.role')),
                ('status_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolestatus')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
