# Generated by Django 5.2.7 on 2025-10-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='priority_id',
            field=models.ForeignKey(blank=True, db_column='priority_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.prioritycategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_id',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolestatus'),
        ),
    ]
